kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cloudcmd-on-server2
  namespace: opencv-cluster-1
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cloudcmd-on-server2
  template:
    metadata:
      labels:
        component: cloudcmd-on-server2
    spec:
      containers:
      - name: cloudcmd-server2-container
        image: coderaiser/cloudcmd
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /mnt/pod-fs
          name: pod-volume
      volumes:
      - name: pod-volume
        hostPath:
          path: /
      nodeSelector:
        cluster2-node: server2

---

kind: Service
apiVersion: v1
metadata:
  name: cloudcmd-server2-service
  namespace: opencv-cluster-1
spec:
  selector:
    component: cloudcmd-on-server2
  ports:
  - name: cloudcmd-server2-port
    port: 8000
    targetPort: 8000
    nodePort: 32401
  type: NodePort
