apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander-deployment
  namespace: opencv-cluster-1
spec:
  selector:
    matchLabels:
      app: redis-commander
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: opencv-cluster-1-cfg
              key: REDIS-SERVICE-HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: opencv-cluster-1-cfg
              key: REDIS-SERVICE-PORT
        ports:
        - containerPort: 8081
          name: http-listener
      nodeSelector:
        redis-server: singlenode
