apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
  namespace: opencv-cluster-1
spec:
  selector:
    app: redis-commander
  ports:
  - name: redis-commander-listener
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 32380
  type: NodePort
