apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    app: redis-server
  ports:
  - name: redis-listener
    protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 32379
  type: NodePort
